In [21]:
from tensorflow.keras.models import load_model
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import tensorflow as tf
import seaborn as sns
import os
import cv2
import matplotlib.gridspec as gridspec
from random import randint
from sklearn.utils import shuffle
from tensorflow import keras
import matplotlib.image as mpimg

tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)

False

In [2]:
model = load_model("model.h5", compile = True)

model.compile(optimizer = 'adam',
            loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True),
                                                                metrics = ['accuracy'])


In [18]:
test_path = 'test'

batch_size = 64
size = 80

test = tf.keras.preprocessing.image_dataset_from_directory(
    test_path,
    image_size = (size, size),
    batch_size = batch_size,
)


class_names = test.class_names
print(labels)

AUTOTUNE = tf.data.experimental.AUTOTUNE
test = test.cache().shuffle(1000).prefetch(buffer_size = AUTOTUNE)

Found 4680 files belonging to 18 classes.
{'100': 0, '120': 1, '140': 2, '160': 3, '180': 4, '20': 5, '200': 6, '220': 7, '240': 8, '260': 9, '280': 10, '300': 11, '320': 12, '340': 13, '360': 14, '40': 15, '60': 16, '80': 17}


In [9]:
ttrain_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)
test_generator = train_datagen.flow_from_directory('test')

labels = (test_generator.class_indices); labels

Found 4680 images belonging to 18 classes.


{'100': 0,
 '120': 1,
 '140': 2,
 '160': 3,
 '180': 4,
 '20': 5,
 '200': 6,
 '220': 7,
 '240': 8,
 '260': 9,
 '280': 10,
 '300': 11,
 '320': 12,
 '340': 13,
 '360': 14,
 '40': 15,
 '60': 16,
 '80': 17}

In [55]:
print("Accuracy of the model on Testing Data is - " , model.evaluate(test)[1]*100 , "%")

74/74 [==============================] - 2s 29ms/step - loss: 1.9815 - accuracy: 1.0000
Accuracy of the model on Testing Data is -  100.0 %


In [11]:
img = [
    'test/20/0RE6HB5.jpg',
    'test/20/0RE6HB6.jpg',
    'test/20/0RE6HB7.jpg',
    'test/180/0RE6HB11.jpg',
    'test/180/0RE6HB12.jpg',
]

image_list = [Image.open(image_path) for image_path in img];
image_list



image_size = (size, size)
test_batch = np.stack([preprocess_input(np.array(img.resize(image_size))) for img in image_list])
test_batch.shape

(5, 80, 80, 3)

In [12]:
pred_probs = model.predict_on_batch(test_batch)

In [13]:
np.argmax(pred_probs, axis=1)

array([5, 5, 5, 4, 4])

In [14]:
labels

{'100': 0,
 '120': 1,
 '140': 2,
 '160': 3,
 '180': 4,
 '20': 5,
 '200': 6,
 '220': 7,
 '240': 8,
 '260': 9,
 '280': 10,
 '300': 11,
 '320': 12,
 '340': 13,
 '360': 14,
 '40': 15,
 '60': 16,
 '80': 17}

In [19]:
x = 'test/80/8D0DKJ5.jpg'

img = keras.preprocessing.image.load_img(
    x, target_size=(size, size)
)
img_array = keras.preprocessing.image.img_to_array(img)
img_array = tf.expand_dims(img_array, 0)

predictions = model.predict(img_array)
score = tf.nn.softmax(predictions[0])

print(
    "the image belongs to {} with a confidence of {:.2f} percent."
    .format(class_names[np.argmax(score)], 100 * np.max(score))
)


the image belongs to 80 with a confidence of 13.79 percent.


In [88]:

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
y_pred = np.argmax(model.predict(test), axis=-1)
print(y_pred[:15])

y_test = np.argmax(labels, axis = 1)
print(y_test[:15])


[13  8 12  3 12  1 11 10 13  3  1 13  7 10  8]


AxisError: axis 1 is out of bounds for array of dimension 1

array([array([ 5,  6,  4, 11,  4, 10,  7, 13, 17,  3, 13,  9,  2,  8,  7, 14, 13,
       10,  1, 10,  8, 13, 10, 14, 15, 16,  7,  8,  4, 10, 11, 15, 10, 15,
        6,  6,  4,  6, 14, 14, 16,  9, 12, 17, 12, 12, 17, 10,  2,  3, 13,
       11,  2,  3,  1, 17,  5,  2, 15,  8,  0, 12,  7,  7], dtype=int32),
       array([12, 17,  6,  7, 16,  5, 12, 14, 15,  0, 11,  6, 16,  6, 12,  3, 16,
        1,  7,  2,  1, 14, 10,  9, 17,  6,  6, 13,  5,  4,  5,  0,  3, 14,
        8, 15,  8, 11,  9,  5,  9, 15, 10,  4, 12, 14,  0,  4,  8, 16, 12,
       14, 13,  8,  7,  7,  0, 11, 16, 14, 17, 13,  1,  7], dtype=int32),
       array([ 6, 10, 11, 10, 15,  3, 14,  4,  9,  6,  0, 12, 15, 16, 12,  5, 12,
        7,  5, 14,  7, 12,  8, 17,  1,  4,  9,  8,  1,  7,  5, 15, 12,  1,
       15, 14, 15,  1, 11, 12,  0, 16, 13,  3, 12,  4,  5,  4,  8, 11,  4,
        5,  8,  4, 12,  6, 14,  0, 13,  4, 15, 14,  6,  9], dtype=int32),
       array([10,  9,  2,  3,  5,  3,  0,  2,  4,  5,  6, 10,  5, 12,  5,  5, 16,
